mysql:
  image: mysql:5.7
  ports:
    - "18100:3306"
  container_name: flagr-mysql
  environment:
    - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    - MYSQL_DATABASE=flagr
    - MYSQL_USER=root
  volumes:
    - ./_data/mysql:/var/lib/mysql

elk:
  image: sebp/elk
  container_name: flagr-elk
  ports:
    - "5601:5601"
    - "9200:9200"
    - "5044:5044"
