mysql:
  image: mysql:5.6
  ports:
    - "18100:3306"
  environment:
    - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    - MYSQL_DATABASE=flagr
    - MYSQL_USER=root
  volumes:
    - ./_data/mysql:/var/lib/mysql
