# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: checkr/flagr-ci
      - image: spotify/kafka
        ports:
          - 2181:2181
          - 9092:9092
        environment:
          ADVERTISED_HOST: localhost
          ADVERTISED_PORT: '9092'
    working_directory: /go/src/github.com/checkr/flagr
    steps:
      - checkout
      - run: make deps
      - run: make test
      - run: bash <(curl -s https://codecov.io/bash)
      - run: cd browser/flagr-ui && yarn install && yarn run test
