[DB]
DBDriver = "mysql"
DBConnectionStr = "root:@tcp(127.0.0.1:18100)/flagr?parseTime=true"

[CORS]
Enabled = true

[Sentry]
Enabled = false
DSN = ""

[EvalCache]
RefreshTimeout = "59s"
RefreshInterval = "5s"
